- name: File=haproxy.yml Update Centos and OpenStack and Install haproxy
  hosts: haproxy
  user: cloud
  sudo: True 
  vars_files:
    - vars.yaml
  tasks:
  #   - name: update ubuntu
  #     shell: sudo apt-get -y update
     - name: Install haproxy
       shell: sudo yum -y install haproxy 
     - name: copy haproxy.cfg
       copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
     - name: Restart haproxy service
       shell: sudo service haproxy restart

